
interfaces:
  spine01:
    bridges:
      - name: "br0"
        members: ["peerlink", "bond1", ]
    peerlink:
      - name: "peerlink"
        members: ["swp31", "swp32"]
        clag_ip: "169.254.254.1"
    bond1:
      - name: "bond1"
        members: ["swp1", "swp2"]
        clag_id: "1"
  spine02:
    bridges:
      - name: "br0"
        members: ["peerlink", "bond1"]
    peerlink:
      - name: "peerlink"
        members: ["swp31", "swp32"]
        clag_ip: "169.254.254.2"
    bond1:
      - name: "bond1"
        members: ["swp1", "swp2"]
        clag_id: "1"
  leaf01:
    bridges:
      - name: "br0"
        members: ["peerlink", "host_clag"]
    peerlink:
      - name: "peerlink"
        members: ["swp49", "swp50"]
        clag_ip: "169.254.254.1"
    host_clag:
      - name: "host_clag"
        members: ["swp1", "swp2"]
        clag_id: "5"
  leaf02:
    bridges:
      - name: "br0"
        members: ["peerlink", "host_clag"]
    peerlink:
      - name: "peerlink"
        members: ["swp49", "swp50"]
        clag_ip: "169.254.254.2"
    host_clag:
      - name: "host_clag"
        members: ["swp1", "swp2"]
        clag_id: "5"


addresses:
  spine01:
    clag_ip: "169.254.254.1/30"
    clag_peer: "169.254.254.2"
    clag_mac: "44:38:39:ff:00:01"
    svi: "10.1.10.252/24"
  spine02:
    clag_ip: "169.254.254.2/30"
    clag_peer: "169.254.254.1"
    clag_mac: "44:38:39:ff:00:01"
    svi: "10.1.10.253/24"
  leaf01:
    clag_ip: "169.254.254.1/30"
    clag_peer: "169.254.254.2"
    clag_mac: "44:38:39:ff:00:02"
    svi: "10.1.10.1/24"
  leaf02:
    clag_ip: "169.254.254.2/30"
    clag_peer: "169.254.254.1"
    clag_mac: "44:38:39:ff:00:02"
    svi: "10.1.10.2/24"

  server01:
    vl1: "10.1.1.12"
    vl10: "10.1.10.12"
    gw: "10.1.10.254"
  server02:
    vl1: "10.1.1.34"
    vl10: "10.1.10.34"
    gw: "10.1.10.254"

vrr:
  spine01:
    vip: "10.1.10.254"
    vmac: "00:11:22:33:44:55"
  spine02:
    vip: "10.1.10.254"
    vmac: "00:11:22:33:44:55"
