- name: do not allow dhcp to send out a default route for anyone
  lineinfile: dest=/etc/dhcp/dhcpd.pools line="#option routers 192.168.0.254;" regexp="^option routers"
  delegate_to: localhost

- name: restart isc-dhcp-server
  service: name=isc-dhcp-server state=restarted pattern=/var/run/dhcp-server/dhcpd.pid
  delegate_to: localhost

- name: verify isc-dhcp-server is running
  service: name=isc-dhcp-server state=started pattern=/var/run/dhcp-server/dhcpd.pi
  delegate_to: localhost  
  
- name: install required packages
  apt: name='{{ item }}' state=present cache_valid_time=86400 update_cache=yes
  with_items:
    - apt-cacher-ng
  delegate_to: localhost

- name: restart the apt-cacher-ng
  service: name=apt-cacher-ng state=restarted pattern=/var/run/apt-cacher-ng/pid
  delegate_to: localhost

- name: verify apt-cacher is running
  service: name=apt-cacher-ng state=started pattern=/var/run/apt-cacher-ng/pid
  delegate_to: localhost
  
