- name: reload networking
  service: name=networking state=reloaded

- name: restart quagga
  service: name=quagga state=restarted

- name: restart vxsnd
  shell: "service vxsnd restart"
  
- name: restart vxrd
  shell: "service vxrd restart"
  
